# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"practice": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://kensugino.github.io/dask_rnaseq/"

git_url = "https://github.com/kensugino/dask_rnaseq/tree/master/"

def custom_doc_links(name): return None
