# AUTOGENERATED! DO NOT EDIT! File to edit: 02_seqs.ipynb (unless otherwise specified).

__all__ = ['seqs']

# Cell
# various sequeces
from .hdict import HBox

seqs = HBox(
    SS3 = HBox(
        # 3' end
        RTP ='ACGAGCATCAGCAGCATACGATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTVN',  # oligo dT
        # 5' end
        TSO ='AGAGACAG ATTGCGCAATG NNNNNNNNrGrGrG',  # TSO
        FP = 'TCGTCGGCAGCGTCAGATG TGTATA AGAGACAG ATTGCGCAATG',  # Forward primer
        TAG = 'ATTGCGCAATG',
        ISPCR = 'AAGCAGTGGTATCAACGCAGAGT',
        #eTAG = 'AGAGACAGATTGCGCAATG',
        # ATTGCGCAATG: "tag"
    ),
    Illumina = HBox(
        NPA =  'AATGATACGGCGACCACCGA GATCTACAC [i5_8bp] TCGTCGGCAGCGTCAGATG', #Nextera_Primer_A
        #Nextera_Primer_A_Universal
        NPAU = 'AATGATACGGCGACCACCGAGATCTACAC',
        #Nextera_Primer_B
        NPB = 'CAAGCAGAAGACGGCATACG AGAT [i7_8bp] GTCTCGTGGGCTCGGAGATGTGTAT',
        #fc1 = 'AATGATACGGCGACCACCGA', # flow cell oligo
        #fc2 = 'CAAGCAGAAGACGGCATACG',
        seq1 = 'TCGTCGGCAGCGTC AGATG TGTATAAGAGACAG',
        seq2 = 'GTCTCGTGGGCTCGGAGATG TGTATAAGAGACAG',
    ),
)